server:   
      port: 9992
spring:
      application:
            name: consumer

#启动熔断开关
feign:
      hystrix:
            enabled: true

eureka:
      client:
            serviceUrl:
                  defaultZone: http://localhost:9999/eureka/