server:   
      port: 9997
spring:
      cloud:
            config:
                  uri: http://127.0.0.1:9998
                  name: config
                  profile: dev
                  label: master
                  discovery:
                        enabled: true
                        serviceId: config
      application:
            name: app

eureka:
      client:
            serviceUrl:
                  defaultZone: http://localhost:9999/eureka/